<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/


$currDir = dirname(__FILE__);
include("$currDir/settings-manager.php");
detect_config();
migrate_config();